name: Deploy to Cloud Run using Docker Hub

on:
  push:
    branches:
      - main  # Deploy only when code is pushed to `main`

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/invoice-full-item:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/invoice-full-item:$IMAGE_TAG

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |
          # Decode the Base64 credentials and save as a temporary file
          echo "${{ secrets.CREDENTIALS_JSON }}" | base64 --decode > /tmp/credentials.json

          # Activate service account with the decoded credentials file
          gcloud auth activate-service-account --key-file /tmp/credentials.json

          # Deploy to Cloud Run
          gcloud run deploy invoice-full-item \
            --image docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/invoice-full-item:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet \
            --timeout=300 \
            --port 8080 \
            --set-env-vars SHEET_ID="${{ secrets.SHEET_ID }}"
